Repository bfgroup/b2, pull requests merged in 2023-04, with the labels that each got.

#223 Scan assembler files for C Preprocessor includes
  src/tools/types/asm.jam
Labels: enhancement, backport version/4.10.0

#225 Inherit generator overrides from a base toolset
  src/build/generators.jam
  src/build/toolset.jam
  src/tools/acc.jam
  src/tools/clang-darwin.jam
  src/tools/clang-linux.jam
  src/tools/clang-vxworks.jam
  src/tools/clang-win.jam
  src/tools/como-linux.jam
  src/tools/cray.jam
  src/tools/darwin.jam
  src/tools/diab.jam
  src/tools/embarcadero.jam
  src/tools/gcc.jam
  src/tools/hp_cxx.jam
  src/tools/intel-darwin.jam
  src/tools/intel-linux.jam
  src/tools/intel-vxworks.jam
  src/tools/intel-win.jam
  src/tools/mipspro.jam
  src/tools/pathscale.jam
  src/tools/pgi.jam
  src/tools/qcc.jam
  src/tools/sun.jam
  src/tools/unix.jam
  src/tools/vacpp.jam
  src/tools/vmsdecc.jam
  src/tools/xlcpp.jam
Labels: bug, enhancement, backport version/4.10.0

#226 Add linemarkers feature: emit/omit line directives
  src/tools/cray.jam
  src/tools/features/linemarkers-feature.jam
  src/tools/gcc.jam
  src/tools/msvc.jam
  src/tools/vmsdecc.jam
  test/preprocessor.py
Labels: enhancement, backport version/4.10.0

#233 fix openssl name handling
  src/tools/openssl.jam
Labels: bug, enhancement, backport version/4.10.0

#227 clang-win: fix assembler path deducing
  src/tools/clang-win.jam
Labels: bug, backport version/4.10.0

#230 Fix toolset subfeature requirements inheritance
  src/build/generators.jam
Labels: bug, backport version/4.10.0

#228 clang-linux: unify compile and link with gcc
  src/tools/clang-linux.jam
  src/tools/gcc.jam
  test/toolset-mock/src/clang-linux-3.9.0.py
Labels: enhancement, backport version/4.10.0

#231 msvc: fix -I"" for same directory pch header
  src/tools/msvc.jam
  test/pch.py
Labels: bug, backport version/4.10.0

#242 Implement --durations - reports top targets by execution time
  src/build-system.jam
  src/util/doc.jam
Labels: enhancement, backport version/4.10.0

#246 clang-darwin: inherit from clang-linux and unify compile
  src/tools/clang-darwin.jam
  test/test_all.py
  test/toolset-mock/src/clang-3.9.0-darwin.py
Labels: enhancement, backport version/4.10.0

#250 clang-linux: don't override RPATH_OPTION
  src/tools/clang-linux.jam
  test/toolset-mock/src/clang-linux-3.9.0.py
Labels: bug, backport version/4.10.0

#252 test suite: don't open with U mode on python 3
  test/BoostBuild.py
Labels: bug, backport version/4.10.0

#259 `<build>no` conditionals evaluation short circuiting
  src/build/property.jam
  test/configure.py
Labels: bug, backport version/4.10.0

#254 inherit-overrides: fix same toolset overrides
  src/build/generators.jam
Labels: bug, backport version/4.10.0

#256 CI: macos gcc tests runner
  .ci/azp-macos-extra.yml
  .ci/azp-macos-test.yml
  azure-pipelines.yml
  src/engine/execunix.cpp
  test/BoostBuild.py
Labels: enhancement, backport version/4.10.0

#224 Assembly preprocessing
  src/build/generators.jam
  src/tools/gcc.jam
  src/tools/generators/c-preprocessing-generator.jam
  src/tools/types/asm.jam
  test/lang_asm.py
  test/test_all.py
Labels: enhancement, backport version/4.10.0

#257 unify gcc and clang-linux soname option
  src/tools/clang-linux.jam
  src/tools/gcc.jam
  test/toolset-mock/src/gcc-4.8.3-linux.py
Labels: enhancement, backport version/4.10.0

#264 Check docs are used
  doc/src/reference.adoc
  test/docs.py
  test/test_all.py
Labels: documentation, enhancement, backport version/4.10.0

#267 Multiprocessing tests runner
  test/test_all.py
Labels: enhancement, backport version/4.10.0

#253 test suite: msys/cygwin fixes
  bootstrap.sh
  src/tools/link.jam
  test/BoostBuild.py
  test/TestToolset.py
  test/builtin_readlink.py
  test/library_chain.py
  test/link.py
  test/prebuilt/ext/jamfile2.jam
  test/prebuilt/ext/jamfile3.jam
  test/searched_lib.py
Labels: bug, backport version/4.10.0

#274 mock tests without compiled wrappers
  test/TestToolset.py
  test/toolset-mock/project-config.jam
  test/toolset-mock/src/Jamroot.jam
  test/toolset-mock/src/mock-program.cpp
Labels: enhancement, backport version/4.10.0

#275 test suite: use python builtin difflib library
  test/BoostBuild.py
Labels: enhancement, backport version/4.10.0

#273 gcc: unify mingw linking
  src/tools/clang-linux.jam
  src/tools/gcc.jam
Labels: enhancement, backport version/4.10.0

#277 pdb order issues tentative fix
  src/build/generators.jam
  src/build/virtual-target.jam
  src/tools/msvc.jam
  test/BoostBuild.py
  test/tag.py
Labels: bug, os:windows, backport version/4.10.0

#281 unify clang-darwin linking with gcc
  src/tools/clang-darwin.jam
  src/tools/gcc.jam
  test/toolset-mock/src/clang-3.9.0-darwin.py
  test/toolset-mock/src/gcc-4.2.1-darwin.py
Labels: enhancement, backport version/4.10.0

#284 mingw/msys/cygwin winthreads/pthread fixes
  src/tools/clang-linux.jam
  src/tools/features/threadapi-feature.jam
  src/tools/gcc.jam
  test/BoostBuild.py
  test/TestToolset.py
  test/toolset-mock/src/clang-linux-3.9.0.py
Labels: bug, backport version/4.10.0
